theme: jekyll-theme-cayman
title: OmegaGraf
description: Fast & Easy vCenter Monitoring Deployment
show_downloads: true
logo: https://raw.githubusercontent.com/OmegaGraf/OmegaGraf/master/docs/branding/logo/dist/logo_1024_light.png
github:
  is_project_page: true
  repository_url: https://github.com/OmegaGraf/OmegaGraf
  zip_url: https://github.com/OmegaGraf/OmegaGraf/releases/download/v1.0.0/OmegaGraf-win-x64-v1.0.0.zip
  tar_url: https://github.com/OmegaGraf/OmegaGraf/releases/download/v1.0.0/OmegaGraf-linux-x64-v1.0.0.tar.gz
github_pages:
  url: https://omegagraf.github.io
  name: omegagraf.github.io